apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: msb
spec:
  backoffLimit: 12
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: docker.io/library/msb-api:day4
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: msb-api-config
            - secretRef:
                name: msb-runtime
          command:
            - python
            - -m
            - api.app.init_db
